[package]
name = "naive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
phf = { version = "0.11.1", features = ["macros"] }
lazy_static = "1.4.0"
dict = "0.1.5"
